services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.1
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./.data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-huggingface'
      ENABLE_MODULES: 'text2vec-huggingface'
      CLUSTER_HOSTNAME: 'node1'
